CREATE DATABASE IF NOT EXISTS medline;
USE medline;

CREATE TABLE IF NOT EXISTS citation (
        citation_id INT AUTO_INCREMENT PRIMARY KEY,
        pubmed_id       VARCHAR(10) UNIQUE NOT NULL,
        title   VARCHAR(500) CHARSET utf8 NOT NULL,
        abstract VARCHAR(10000) CHARSET utf8 NULL
);

CREATE TABLE IF NOT EXISTS sentence (
	sentence_id INT AUTO_INCREMENT PRIMARY KEY,
	citation_id INT NOT NULL REFERENCES citation,
	offset INT UNSIGNED NOT NULL,
	length INT UNSIGNED NOT NULL,
	type VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS mention (
	mention_id INT AUTO_INCREMENT PRIMARY KEY,
	sentence_id INT UNSIGNED NOT NULL REFERENCES sentence,
	offset INT UNSIGNED NOT NULL,
	length INT UNSIGNED NOT NULL,
	type VARCHAR(40) NOT NULL,
	text VARCHAR(500) CHARSET utf8 NOT NULL
);


